spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ecommerce_database
        username: root
        password: Lp#431992
    jpa:
        hibernate.ddl-auto: update
        generate-ddl: true
        show-sql: true